Dir.chdir File.dirname __FILE__

file :mruby do
  sh "git clone --depth=1 git://github.com/mruby/mruby.git"
end

task :test => :mruby do
  sh "cd mruby && MRUBY_CONFIG=#{File.expand_path "build_config.rb"} rake test"
end

task :clean do
  sh "cd mruby && rake deep_clean"
end

task :default => :test